[package]
name = "rust_project"
version = "0.1.0"
authors = ["stijn-volckaert","ruben-mechelinck"]

[dependencies]
libc="0.2"
time="0.2"
ctrlc="3.1.8"
simple-error="0.2.3"
shuteye="0.3.3"
mmap="0.1.1"
nix="0.20.0"
byteorder="1"